### ISSUE TITLE
Buttons for each hosting type

### ISSUE THREAD

**Issue by PatelN123** [Sivu-Tutorials/website#8]
Adds buttons for each hosting type. Netlify, Koyeb etc...
On this page: https://beta.sivu.tk/docs/getting-started

**Comment by RakeshPotnuru** [comment]
@PatelN123 Can you give some description?

**Comment by PatelN123** [comment]
Sure,

![IMG_20220620_074850.jpg](https://user-images.githubusercontent.com/79650289/174541637-6d4fb1ae-4917-44d3-b5bb-4ec63e8b51d9.jpg)

For example where we have these, they should be buttons to go to the website for that service.
